version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    volumes:
      - ${PWD}/soccer-friends:/var/www/html
    depends_on:
      - db
    entrypoint: /bin/bash
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:FxrPbHLH5ludrQ6KIkxAC/reBDkoZhj6SqkMU/7tRCA=
      APP_DEBUG: "true"
      APP_URL: http://localhost
      LOG_CHANNEL: stack
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: username
      DB_PASSWORD: password

  web:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - "80:80"
      - "9000:9000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:FxrPbHLH5ludrQ6KIkxAC/reBDkoZhj6SqkMU/7tRCA=
      APP_DEBUG: "true"
      APP_URL: http://localhost
      LOG_CHANNEL: stack
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: username
      DB_PASSWORD: password

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "your_email@example.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    depends_on:
      - db
    links:
      - db:postgres

volumes:
  pgdata:
