version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    entrypoint: /bin/bash
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:FxrPbHLH5ludrQ6KIkxAC/reBDkoZhj6SqkMU/7tRCA=
      APP_DEBUG: "true"
      APP_URL: http://localhost
      LOG_CHANNEL: stack
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: username
      DB_PASSWORD: password


  web:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:FxrPbHLH5ludrQ6KIkxAC/reBDkoZhj6SqkMU/7tRCA=
      APP_DEBUG: "true"
      APP_URL: http://localhost
      LOG_CHANNEL: stack
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: username
      DB_PASSWORD: password

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
